export const NUMBER_OF_PRIVATE_OBJECTIVES = 1;
export const NUMBER_OF_PUBLIC_OBJECTIVES = 2;
export const NUMBER_OF_UNIQUE_OBJECTIVES = NUMBER_OF_PUBLIC_OBJECTIVES + 2 * NUMBER_OF_PRIVATE_OBJECTIVES;
